/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InfoUpdater */

#ifndef _Included_InfoUpdater
#define _Included_InfoUpdater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InfoUpdater
 * Method:    getSystemTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InfoUpdater_getSystemTime
  (JNIEnv *, jclass);

/*
 * Class:     InfoUpdater
 * Method:    getSessionTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InfoUpdater_getSessionTime
  (JNIEnv *, jclass);

/*
 * Class:     InfoUpdater
 * Method:    getPriorities
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InfoUpdater_getPriorities
  (JNIEnv *, jclass);

/*
 * Class:     InfoUpdater
 * Method:    getTPriorities
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InfoUpdater_getTPriorities
  (JNIEnv *, jclass);

/*
 * Class:     InfoUpdater
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InfoUpdater_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
