/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MemoryController */

#ifndef _Included_MemoryController
#define _Included_MemoryController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MemoryController
 * Method:    globalMemoryStatus
 * Signature: ()LMemoryStatus;
 */
JNIEXPORT jobject JNICALL Java_MemoryController_globalMemoryStatus
  (JNIEnv *, jclass);

/*
 * Class:     MemoryController
 * Method:    getProcesses
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_MemoryController_getProcesses
  (JNIEnv *, jclass, jobject);

/*
 * Class:     MemoryController
 * Method:    getMemoryMap
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_MemoryController_getMemoryMap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
